name: Sentry source maps

on:
  push:
    branches:
      - master

jobs:
  push-source-maps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm ci --cache .npm --prefer-offline
      - run: "npm run build:ci"
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
